apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sulu.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sulu.name" . }}
    helm.sh/chart: {{ include "sulu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.sulu.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sulu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sulu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.sulu.image.repository }}:{{ .Values.sulu.image.tag }}"
          imagePullPolicy: {{ .Values.sulu.image.pullPolicy }}
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/var/uploads
              subPath: var/uploads
            - name: uploads
              mountPath: /var/www/html/public/uploads
              subPath: public/uploads
          env:
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              value: {{ .Values.sulu.secret }}
            - name: SULU_ADMIN_EMAIL
              value: {{ .Values.sulu.email }}
            - name: VARNISH_SERVER
              value: {{ template "sulu.varnish.fullname" . }}
            - name: REDIS_HOST
              value: {{ template "sulu.redis.fullname" . }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            - name: DATABASE_HOST
              value: {{ template "sulu.mysql.fullname" . }}
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: {{ .Values.mysql.mysqlDatabase | quote }}
            - name: DATABASE_USER
              value: {{ .Values.mysql.mysqlUser | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.mysql.mysqlPassword | quote }}
#              Secret will be recreated on upgrade
#              https://github.com/helm/charts/issues/5167
#              valueFrom:
#                  secretKeyRef:
#                      name: {{ template "sulu.mysql.fullname" . }}
#                      key: mysql-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.sulu.resources | indent 12 }}
      volumes:
        - name: uploads
          {{- if .Values.sulu.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.sulu.persistence.existingClaim | default (include "sulu.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end -}}
    {{- with .Values.sulu.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.sulu.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.sulu.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
