{{- if .Values.varnish.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sulu.varnish.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sulu.name" . }}
    helm.sh/chart: {{ include "sulu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.varnish.service.type }}
  ports:
    - port: {{ .Values.varnish.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sulu.name" . }}-varnish
    app.kubernetes.io/instance: {{ .Release.Name }}-varnish
{{- end }}
