apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sulu-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sulu-chart.name" . }}
    helm.sh/chart: {{ include "sulu-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sulu-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sulu-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              value: "asdfasdfsdf"
            - name: SULU_ADMIN_EMAIL
              value: "info@sulu.io"
            - name: DATABASE_HOST
              value: {{ template "sulu-chart.mysql.fullname" . }}
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: {{ .Values.mysql.mysqlDatabase | quote }}
            - name: DATABASE_USER
              value: {{ .Values.mysql.mysqlUser | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "sulu-chart.mysql.fullname" . }}
                  key: mysql-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
